version: '3.7'

services:
  app:
    build: .
    container_name: nestjs-partner-api
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    container_name: nestjs-partner-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
    ports:
      - 3306:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 1m30s
      timeout: 10s
      start_period: 40s
      retries: 3


volumes:
  mysql:
    driver: local